services:
  auth-staging:
    hostname: auth-staging
    image: artixteam/auth-staging:latest
    restart: on-failure
    ports:
      - "8001:8001"
    env_file:
      - .env.local
    networks:
      - backend
    volumes:
      - ./auth:/app/auth
      - /app/auth/node_modules
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: localhost:24224
        tag: auth-staging
  
networks:
  backend:
    driver: bridge